// <auto-generated />
using System;
using Demo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Demo.Domain.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time_Zone")
                        .HasColumnType("TEXT");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Demo.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventCodeDefinitionEventCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Event_Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("EventCode");

                    b.HasIndex("EventCodeDefinitionEventCode");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Demo.Domain.Entities.EventCodeDefinition", b =>
                {
                    b.Property<string>("EventCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Long_Description")
                        .HasColumnType("TEXT");

                    b.HasKey("EventCode");

                    b.ToTable("EventCodeDefinitions");
                });

            modelBuilder.Entity("Demo.Domain.Entities.Event", b =>
                {
                    b.HasOne("Demo.Domain.Entities.City", "City")
                        .WithMany("Events")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Demo.Domain.Entities.EventCodeDefinition", "EventCodeDefinition")
                        .WithMany()
                        .HasForeignKey("EventCode");

                    b.HasOne("Demo.Domain.Entities.EventCodeDefinition", null)
                        .WithMany("Events")
                        .HasForeignKey("EventCodeDefinitionEventCode");

                    b.Navigation("City");

                    b.Navigation("EventCodeDefinition");
                });

            modelBuilder.Entity("Demo.Domain.Entities.City", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Demo.Domain.Entities.EventCodeDefinition", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
